name: daytum
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.5.1
  - matplotlib=3.10.8
  - notebook=6.5.7
  - numba=0.63.1
  - numpy=2.3.5
  - optax=0.2.6
  - pandas=2.3.3
  - pip=25.3
  - python=3.14.2
  - scipy=1.16.3
  - seaborn=0.13.2
  - tqdm=4.67.1
  - ipywidgets=8.1.8
  - jax=0.7.2
  - jaxlib=0.7.2
  - jupyter_contrib_nbextensions=0.7.0
  - scikit-learn=1.8.0
  - astropy=7.2.0
  - alphashape=1.3.1
  - pip:
      - geostatspy==0.0.79
      - pydotplus==2.0.2
      - shap==0.50.0
